import os
import json
import csv
import hashlib
import duckdb
from pathlib import Path
from typing import Dict, List, Any, Set
from config import DB_PATH, OUTPUT_DIR
from utils import logger

# Canonical concepts description
CANONICAL_CONCEPTS = {
    "Scope1Emission": "Direct greenhouse gas emissions from sources owned or controlled by the organization.",
    "Scope2Emission": "Indirect greenhouse gas emissions from the generation of purchased electricity, heating, cooling, or steam consumed by the organization.",
    "RenewableEnergy": "Total energy consumed from renewable sources such as solar, wind, hydro, biomass, and geothermal.",
    "WaterWithdrawal": "Total volume of water drawn from all sources (surface water, groundwater, seawater, or third-party water) for consumption or operations.",
    "WasteGenerated": "Total amount of all waste generated by operations, including hazardous and non-hazardous wastes.",
    "WomenEmployees": "Total number or percentage of women employees and workers within the organization.",
    "BoardIndependence": "Metrics indicating the composition of the board, independence level, and oversight capabilities (including gender diversity as proxy).",
    "CSRSpending": "Total monetary amount spent on Corporate Social Responsibility (CSR) projects and community investments."
}

# Mapping BRSR concepts from the DuckDB warehouse to canonical concepts
BRSR_MAPPINGS = {
    "TotalScope1Emissions": "Scope1Emission",
    "TotalScope2Emissions": "Scope2Emission",
    "TotalEnergyConsumedFromRenewableSources": "RenewableEnergy",
    "TotalVolumeOfWaterWithdrawal": "WaterWithdrawal",
    "TotalWasteGenerated": "WasteGenerated",
    "NumberOfFemaleEmployeesOrWorkers": "WomenEmployees",
    "PercentageOfFemaleBoardOfDirectors": "BoardIndependence",
    "AmountSpentForCSRProjectsUndertaken": "CSRSpending"
}

# Categories for canonical concepts
CONCEPT_CATEGORIES = {
    "Scope1Emission": "Environmental",
    "Scope2Emission": "Environmental",
    "RenewableEnergy": "Environmental",
    "WaterWithdrawal": "Environmental",
    "WasteGenerated": "Environmental",
    "WomenEmployees": "Social",
    "BoardIndependence": "Governance",
    "CSRSpending": "Social"
}

# Cross-framework concept mapping dictionary
# Schema: Standard -> { FrameworkTag: CanonicalConcept }
CROSS_STANDARD_MAPPINGS = {
    "GRI": {
        "DirectGHGEmissions": "Scope1Emission",
        "EnergyIndirectGHGEmissions": "Scope2Emission",
        "RenewableEnergyConsumption": "RenewableEnergy",
        "WaterWithdrawalBySource": "WaterWithdrawal",
        "WasteGenerated": "WasteGenerated",
        "DiversityOfEmployees": "WomenEmployees",
        "GovernanceStructureAndComposition": "BoardIndependence",
        "DirectEconomicValueDistributed": "CSRSpending"
    },
    "SASB": {
        "GrossScope1Emissions": "Scope1Emission",
        "GrossScope2Emissions": "Scope2Emission",
        "RenewableEnergyConsumed": "RenewableEnergy",
        "TotalWaterWithdrawn": "WaterWithdrawal",
        "TotalAmountOfWaste": "WasteGenerated",
        "GenderDiversityPercentage": "WomenEmployees",
        "BoardIndependencePercentage": "BoardIndependence",
        "CommunityInvestments": "CSRSpending"
    },
    "ESRS": {
        "ESRS E1-6 Scope 1 GHG Emissions": "Scope1Emission",
        "ESRS E1-6 Scope 2 GHG Emissions": "Scope2Emission",
        "ESRS E1-5 Renewable Energy Consumption": "RenewableEnergy",
        "ESRS E3-1 Water Withdrawal": "WaterWithdrawal",
        "ESRS E5-5 Waste Generated": "WasteGenerated",
        "ESRS S1-9 Gender Diversity": "WomenEmployees",
        "ESRS G1-1 Board Composition": "BoardIndependence",
        "ESRS S3 CSR Activities": "CSRSpending"
    },
    "ISSB": {
        "ISSB S2 Scope 1 GHG Emissions": "Scope1Emission",
        "ISSB S2 Scope 2 GHG Emissions": "Scope2Emission",
        "ISSB S2 Renewable Energy Percentage": "RenewableEnergy",
        "ISSB S1 Water Security Disclosures": "WaterWithdrawal",
        "ISSB S1 Circularity Disclosures": "WasteGenerated",
        "ISSB S1 Diversity Metrics": "WomenEmployees",
        "ISSB S1 Governance Disclosures": "BoardIndependence",
        "ISSB S1 Economic Disclosures": "CSRSpending"
    }
}

class ESGOntologyManager:
    def __init__(self, db_path: Path = DB_PATH, output_dir: Path = OUTPUT_DIR):
        self.db_path = db_path
        self.output_dir = output_dir
        self.nodes: List[Dict[str, Any]] = []
        self.relationships: List[Dict[str, Any]] = []
        self.added_node_ids: Set[str] = set()
        
    def add_node(self, node_id: str, label: str, name: str, **kwargs):
        """Helper to ensure unique node addition."""
        if node_id in self.added_node_ids:
            return
        
        node = {
            "id:ID": node_id,
            "label:LABEL": label,
            "name": name,
            "concept": kwargs.get("concept", ""),
            "value": kwargs.get("value", ""),
            "normalized_value": kwargs.get("normalized_value", ""),
            "value_type": kwargs.get("value_type", ""),
            "unit_ref": kwargs.get("unit_ref", ""),
            "source_file": kwargs.get("source_file", ""),
            "dimensions": kwargs.get("dimensions", ""),
            "description": kwargs.get("description", "")
        }
        self.nodes.append(node)
        self.added_node_ids.add(node_id)

    def add_relationship(self, start_id: str, end_id: str, rel_type: str):
        """Helper to add relationship between nodes."""
        self.relationships.append({
            "start_id:START_ID": start_id,
            "end_id:END_ID": end_id,
            "type:TYPE": rel_type
        })

    def build_ontology_metadata_nodes(self):
        """Build schema nodes (Categories, Standards, Canonical Concepts, Framework Tags)."""
        logger.info("Building ontology metadata nodes...")
        
        # 1. Add Categories
        for cat in ["Environmental", "Social", "Governance", "Other"]:
            self.add_node(f"Category_{cat}", "Category", cat)

        # 2. Add Standards
        for std in ["BRSR", "GRI", "SASB", "ESRS", "ISSB"]:
            self.add_node(f"Standard_{std}", "Standard", std)

        # 3. Add Canonical Concept nodes & associate with categories
        for concept_id, desc in CANONICAL_CONCEPTS.items():
            self.add_node(
                concept_id, 
                "ESGMetric;CanonicalConcept", 
                concept_id, 
                description=desc
            )
            
            # Map to category
            cat = CONCEPT_CATEGORIES.get(concept_id, "Other")
            self.add_relationship(concept_id, f"Category_{cat}", "BELONGS_TO")

        # 4. Add Cross-Standard Framework Tag nodes and map to Canonical Concepts
        for std, tag_map in CROSS_STANDARD_MAPPINGS.items():
            std_node_id = f"Standard_{std}"
            for tag, canonical in tag_map.items():
                tag_node_id = f"Framework_{std}_{tag}"
                # Add framework tag node
                self.add_node(tag_node_id, "ESGMetric;FrameworkTag", tag)
                
                # Relations
                self.add_relationship(tag_node_id, std_node_id, "BELONGS_TO")
                self.add_relationship(tag_node_id, canonical, "MAPS_TO")

    def build_instance_nodes_and_relationships(self):
        """Query DuckDB ESG facts and generate Company, Year, Fact nodes & edges."""
        logger.info(f"Connecting to DuckDB database at {self.db_path}...")
        if not self.db_path.exists():
            raise FileNotFoundError(f"Database not found at {self.db_path}. Please run pipeline first.")
            
        conn = duckdb.connect(str(self.db_path))
        
        # Fetch facts that match our mapped concepts
        query_concepts = list(BRSR_MAPPINGS.keys())
        placeholders = ", ".join(f"'{c}'" for c in query_concepts)
        
        query = f"""
            SELECT 
                company_name, 
                report_year, 
                concept, 
                value, 
                normalized_value, 
                value_type, 
                unit_ref, 
                source_file, 
                dimensions_json,
                category
            FROM esg_facts
            WHERE concept IN ({placeholders})
        """
        
        df = conn.execute(query).df()
        conn.close()
        
        logger.info(f"Retrieved {len(df)} matching ESG facts from DuckDB.")
        
        for idx, row in df.iterrows():
            comp_name = row["company_name"]
            # Extract clean company ID (e.g. TCS)
            comp_id = "TCS" if "tata consultancy" in comp_name.lower() else ("RELIANCE" if "reliance" in comp_name.lower() else "INFOSYS")
            
            # 1. Add Company Node
            self.add_node(comp_id, "Company", comp_name)
            
            # 2. Add Year Node (e.g. Extract 2024 from 2024-04-01)
            raw_year = row["report_year"]
            year_val = raw_year.split("-")[0] if "-" in raw_year else raw_year
            year_node_id = f"Year_{year_val}"
            self.add_node(year_node_id, "Year", year_val)
            
            # Company REPORTS Year
            self.add_relationship(comp_id, year_node_id, "REPORTS")
            
            # 3. Add Fact ESGMetric Instance Node
            concept = row["concept"]
            canonical = BRSR_MAPPINGS.get(concept, "Other")
            
            # Generate unique fact ID based on properties
            fact_raw_str = f"{comp_id}_{concept}_{year_val}_{row['dimensions_json']}_{idx}"
            fact_hash = hashlib.md5(fact_raw_str.encode("utf-8")).hexdigest()[:12]
            fact_node_id = f"Fact_{comp_id}_{concept}_{year_val}_{fact_hash}"
            
            self.add_node(
                fact_node_id,
                "ESGMetric;Fact",
                f"{comp_id} {concept} ({year_val})",
                concept=concept,
                value=str(row["value"]),
                normalized_value=str(row["normalized_value"]) if row["normalized_value"] is not None else "",
                value_type=row["value_type"],
                unit_ref=row["unit_ref"] if row["unit_ref"] is not None else "",
                source_file=row["source_file"],
                dimensions=row["dimensions_json"]
            )
            
            # 4. Generate Relationships for Fact Instance
            # Company HAS_METRIC Fact
            self.add_relationship(comp_id, fact_node_id, "HAS_METRIC")
            
            # Fact DISCLOSED_IN Year
            self.add_relationship(fact_node_id, year_node_id, "DISCLOSED_IN")
            
            # Fact BELONGS_TO Category
            category_name = row["category"] or CONCEPT_CATEGORIES.get(canonical, "Other")
            self.add_relationship(fact_node_id, f"Category_{category_name}", "BELONGS_TO")
            
            # Fact MAPS_TO BRSR Standard
            self.add_relationship(fact_node_id, "Standard_BRSR", "MAPS_TO")
            
            # Fact MAPS_TO Canonical Concept
            self.add_relationship(fact_node_id, canonical, "MAPS_TO")

    def export_csvs(self):
        """Export nodes.csv and relationships.csv to output directory."""
        self.output_dir.mkdir(parents=True, exist_ok=True)
        nodes_path = self.output_dir / "nodes.csv"
        rels_path = self.output_dir / "relationships.csv"
        
        logger.info(f"Exporting nodes to {nodes_path}...")
        # Get all fields for nodes csv
        node_fields = [
            "id:ID", "label:LABEL", "name", "concept", "value", 
            "normalized_value", "value_type", "unit_ref", "source_file", 
            "dimensions", "description"
        ]
        
        with open(nodes_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=node_fields)
            writer.writeheader()
            writer.writerows(self.nodes)
            
        logger.info(f"Exported {len(self.nodes)} nodes successfully.")

        logger.info(f"Exporting relationships to {rels_path}...")
        rel_fields = ["start_id:START_ID", "end_id:END_ID", "type:TYPE"]
        
        with open(rels_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=rel_fields)
            writer.writeheader()
            writer.writerows(self.relationships)
            
        logger.info(f"Exported {len(self.relationships)} relationships successfully.")

    def generate_metadata_summary(self):
        """Export ontology metadata summary to output directory."""
        metadata_path = self.output_dir / "ontology_metadata.json"
        
        # Calculate counts
        node_counts = {}
        for node in self.nodes:
            lbl = node["label:LABEL"]
            node_counts[lbl] = node_counts.get(lbl, 0) + 1
            
        rel_counts = {}
        for rel in self.relationships:
            rtype = rel["type:TYPE"]
            rel_counts[rtype] = rel_counts.get(rtype, 0) + 1
            
        summary = {
            "ontology_version": "1.0.0",
            "canonical_concepts_mapped": list(CANONICAL_CONCEPTS.keys()),
            "standards_included": ["BRSR", "GRI", "SASB", "ESRS", "ISSB"],
            "nodes_count": len(self.nodes),
            "relationships_count": len(self.relationships),
            "node_type_breakdown": node_counts,
            "relationship_type_breakdown": rel_counts,
            "cross_standard_mapped_tags_count": sum(len(tags) for tags in CROSS_STANDARD_MAPPINGS.values())
        }
        
        with open(metadata_path, "w", encoding="utf-8") as f:
            json.dump(summary, f, indent=2)
            
        logger.info(f"Exported ontology metadata summary to {metadata_path}")
        return summary
